name: Reusable workflow for building logic app workflows

on:
  workflow_call:
    inputs:      
      WORKING_DIRECTORY:
        description: "The directory of the logic app"
        required: true
        type: string

jobs:
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    
    steps: 

      - name: Checkout
        uses: actions/checkout@v2

      - name: Package Logic
        run: (mkdir ./output; zip -r ./output/logic.zip .)

      # Upload zipped artifacts to Git Hub
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: logic
          path: '${{ inputs.WORKING_DIRECTORY }}/output/logic.zip'
          if-no-files-found: error
